salsadigitalauorg/lagoon_ansible_collection

api/plugins/action/group.py
api/plugins/action/user_group.py
api/plugins/lookup/group.py
api/plugins/module_utils/api_client.py

- Fix issue with user groups 400 errors.
- Adds lookup plugin for groups
- Adds action plugin for groups.

Add group support.

---

api/plugins/action/deploy_target_config.py
api/plugins/action/environment.py
api/plugins/module_utils/api_client.py
api/plugins/modules/deploy_target_config.py
api/plugins/modules/environment.py

Only delete implemented for now.

Created an environment module.

---

api/plugins/action/environment_update.py
api/plugins/lookup/var.py
api/plugins/module_utils/api_client.py

We're moving away from Openshift, so at some point that might be deprecated. Might as well move now.

Replace openshift by kubernetes.

---

api/plugins/inventory/lagoon.py

Refactor the lagoon inventory plugin.

---

README.md
api/README.md
api/galaxy.yml
api/plugins/action/list.py
api/plugins/action/token.py
api/plugins/action/user_group.py
api/plugins/action/whoami.py
api/plugins/inventory/lagoon.py
api/plugins/lookup/metadata.py
api/plugins/lookup/project.py
api/plugins/lookup/var.py
api/plugins/module_utils/api_client.py
api/plugins/module_utils/gql.py
api/plugins/module_utils/token.py

Refactored the project & var lookup plugins for a start.

Added a simple helper class for gql.

---

api/plugins/inventory/lagoon.py

- Added more helpful errors when the gql query fails.
- Added a helper function to determine a variable from environment, host vars or the lagoon.yml file.
- Also allowed variables without the lagoon_ prefix in the lagoon.yml.

feat: allow batch sizes to be changed using vars

---

api/plugins/module_utils/token.py

on-behalf-of: @dpc-sdp <de.ops@dpc.vic.gov.au>

fix: strip newline from token

---

api/plugins/filter/lagoon.py
api/plugins/lookup/environment.py

refactored environment lookup to use gql

feat: add autogen-route filter

---

api/plugins/action/deploy_bulk.py
api/plugins/filter/lagoon.py

- updated the filter to use environment id by default
- removed lagoon from the filter names, and deprecated the previous ones.

feat: add build vars to each environment

---

api/plugins/action/project.py
api/plugins/action/project_group.py
api/plugins/module_utils/api_client.py

- Create/Delete projects
- Manage project groups

Add project and project_group actions.

---

api/galaxy.yml

With the refactoring of the collections methods of querying a version bump will help with testing etc.

Bumped version number.

---

api/plugins/module_utils/api_client.py
api/plugins/modules/deploy_target_config.py

Changed:
1) Fix timeout when retrieving deploy target config

[DEVOPS-71] Fix timeout when retrieving deploy target config

---

api/plugins/action/deploy.py
api/plugins/module_utils/gqlEnvironment.py

To resolve `The error was: AttributeError: 'builtin_function_or_method' object has no attribute 'sleep'` in `lagoon.api.deploy`.

Import sleep from time.

---

api/plugins/action/deploy_bulk.py
api/plugins/action/fact.py
api/plugins/action/info.py
api/plugins/inventory/lagoon.py
api/plugins/module_utils/display.py
api/plugins/module_utils/gql.py
api/plugins/module_utils/gqlEnvironment.py
api/plugins/module_utils/gqlError.py
api/plugins/module_utils/gqlProject.py
api/plugins/module_utils/gqlResourceBase.py
api/plugins/module_utils/gqlVariable.py
api/tests/unit/plugins/module_utils/test_display.py
api/tests/unit/plugins/module_utils/test_gql.py
api/tests/unit/plugins/module_utils/test_gql_variable.py
docker-compose.yml

[DEVOPS-133] Improve error handling

---

api/plugins/action/metadata.py

- Ensures project_id is an int.

fix: Metadata type conversion.

---

api/plugins/action/fact.py
api/plugins/action/info.py
api/plugins/action/task_definition.py
api/plugins/module_utils/gqlEnvironment.py
api/plugins/module_utils/gqlTask.py
api/plugins/modules/task.py
api/roles/invoke_task/tasks/main.yml
api/tests/unit/requirements.txt

- Improvements & additions to Task.
- Also fixed failing tests.

Add fact category & more

---

api/roles/invoke_task/defaults/main.yml
api/roles/invoke_task/tasks/main.yml

- also introduced a number of variables with sane defaults

feat: additional condition for invoke_task wait

---

api/plugins/action/fact.py
api/plugins/action/problem.py
api/plugins/modules/problem.py
api/roles/common/defaults/main.yml
api/roles/common/tasks/main.yml
api/roles/invoke_task/defaults/main.yml
api/roles/invoke_task/meta/main.yml
api/roles/set_fact/meta/main.yml
api/roles/set_fact/tasks/main.yml
api/roles/set_problem/meta/main.yml
api/roles/set_problem/tasks/main.yml

- moved common defaults to the common role
- added dependencies on common to fact & problem
- added set_fact & set_problem roles

feat: added problem plugin

---

api/README.md
api/plugins/action/task_definition.py
api/plugins/module_utils/gqlTaskDefinition.py
api/tests/common/schema.graphql
api/tests/unit/plugins/module_utils/test_gql_task_definition.py

- Also delete & add again when the task type has changed

[DEVOPS-403] Added fields for task_definition

---

api/plugins/action/mutation.py

- Failed tasks are also complete!

[DEVOPS-646] Fixed wait condition

---

api/plugins/action/task.py
api/plugins/module_utils/gqlTask.py
api/plugins/modules/task.py

Currently, it does not seem possible to pass arguments to task invocation action.
Expand on the existing module and action to allow for arguments to be passed.

[DEVOPS-350] Added possibility to pass arguments to task invocation.
